### ISSUE TITLE
Missind import time package for format: 'date-time'

### ISSUE THREAD

**Issue by komex** [contiamo/openapi-generator-go#83] opened 2022-09-05 09:54 UTC
When adding `format: 'date-time'`, go type correctly changes to `time.Time`, but without importing `time` package.

In:
```yaml
    Date:
      title: 'Date'
      type: string
      format: 'date-time'
```

Out:
```go
// This file is auto-generated, DO NOT EDIT.
//
// Source:
//     Title: API Gateway
//     Version: 3.1.1
package model

// Date is a value type. Pointer to the date
type Date time.Time
```

**Comment by LucasRoesler** [comment] 2022-09-05 12:08
That is weird, we have a test to check for this https://github.com/contiamo/openapi-generator-go/blob/master/pkg/generators/models/testdata/cases/validation/generated/model_person.go

i will dig a little but more

**Comment by LucasRoesler** [comment] 2022-09-05 14:01
@komex is there any chance you can share a sample repo that reproduces the issue? The current tests cover this case and I can find the code where we also handle the imports ([see here](https://github.com/contiamo/openapi-generator-go/blob/master/pkg/generators/models/models.go#L186)) so I am pretty confused because we use `date-time` a lot in our own APIs and have never seen this happen.

**Comment by komex** [comment] 2022-09-05 16:08
@LucasRoesler, you can try to build from this yaml:
```yaml
---
openapi: 3.0.0
info:
  title: 'Test'
components:
    schemas:
      Date:
        title: 'Date'
        description: 'Pointer to the date'
        type: string
        format: 'date-time'
```

**Comment by LucasRoesler** [comment] 2023-05-04 14:59
I haven't been able to reproduce and the existing test seem to cover this, so I am going to close it for now.

**Closed by LucasRoesler** 2023-05-04 14:59 UTC
